name: Release

on:
  push:

  # release:
  #   types:
  #     - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      # Disable tests for now, requires Algod+KMD to be available
      # - name: Run tests
      #   run: poetry run pytest

      - name: Compile contracts
        run: ./build.sh

      # TODO: copy files to release
      - run: ls assets
